### ISSUE TITLE
Relative path patch reverted

### ISSUE THREAD

**Issue by egassemcinatas** [rcls/crap#11]
The patch to allow relative destination paths (commit 09547d1a77) was (probably unintentionally) reverted in commit 5f2ee87eb.  This smells like manual version mangement of crap-clone.c ;-).  You can most easily re-apply the patch with "git cherry-pick 09547d1" on the master branch.

**Comment by rcls** [comment]
Actually, it was intentional. Unfortunately, it was incompatible with how CVS interprets the cvsroot string. CVS allows `cvs -d host/path`.
I haven't implemented all CVS formats for the cvsroot, but the ones I do support, I want to keep compatible with CVS.

**Comment by rcls** [comment]
I have reimplemented this, in a manner compatible with CVS: a cvsroot starting with `./` is a relative path.
Also I have added support for the CVS :fork: and :local: methods, again allowing relative paths.
