### ISSUE TITLE
fatal error: pipeline.h: No such file or directory

### ISSUE THREAD

**Issue by mwat56** [rcls/crap#21]
I tried to compile the program:

    $ make
    gcc -O2 -std=c99 -Wall -Wextra -Werror -D_GNU_SOURCE -g3 -MMD -MP -MF.deps/branch.o.d   -c -o branch.o -c branch.c
    gcc -O2 -std=c99 -Wall -Wextra -Werror -D_GNU_SOURCE -g3 -MMD -MP -MF.deps/changeset.o.d   -c -o changeset.o -c changeset.c
    gcc -O2 -std=c99 -Wall -Wextra -Werror -D_GNU_SOURCE -g3 -MMD -MP -MF.deps/cvs_connection.o.d   -c -o cvs_connection.o -c cvs_connection.c
    cvs_connection.c:10:10: fatal error: pipeline.h: No such file or directory
     #include <pipeline.h>
              ^~~~~~~~~~~~
    compilation terminated.
    Makefile:25: recipe for target 'cvs_connection.o' failed
    make: *** [cvs_connection.o] Error 1

Can you tell me which library I have to install?
Thanks!

**Comment by rcls** [comment]
You need libpipeline.
`apt install libpipeline-dev` on debian or ubuntu. (-devel on RedHat).
http://git.savannah.nongnu.org/cgit/libpipeline.git
