### ISSUE TITLE
Relative paths to local CVS repositories

### ISSUE THREAD

**Issue by egassemcinatas** [rcls/crap#9]
Hi,

the last time I used crap-clone, I thought it would be nice to use tab-completion for the path to a local CVS repository, and to use a relative path.  This (like so many things) is made impossible by a CVS misfeature that requires local repository paths to be absolute and not end in a slash.  Now I have finally found the time to write a patch.  A git bundle is here:

http://volkerschatz.com/tmp/crap-clone-relpath.bundle

It contains just one commit; the patch simply removes trailing slashes and prepends the current working directory when needed.  I hope you consider it useful.

**Comment by rcls** [comment]
Thanks, somehow I neglected this last year, it is now applied.
